# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrename" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "6eacfd71178d5d460e4c96fd8c664a0d480b0717ec0bf5db2e6bd331260d9cae"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "638997ab4e3bd40509c3fb3e5a853aa4bc059ae08b52d3b793e89e1ba9b32769"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9ad88700408aa5edaf0b201e4af47b18b5651aa46f63a1d969aa65442dbaf647"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a1898aed724f4b8a898142f6daffc107544c85b5f9cb4de3a9b75ee158e055d7"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfrename"
  desc "Rename Terraform resources, data sources, modules, variables, outputs, and locals across .tf files"
  homepage "https://github.com/winebarrel/tfrename"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrename"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfrename"]
    end
  end

  # No zap stanza required

end
