# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrename" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "57381f1ec6685338ebde926ca51a987f20772b6a6b4db730f1279c6509df376f"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "508a25958e15253721b89f1e00830e9d0a10a6cf67f80168cf18d980e61642d4"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8276c4d2ca3b362630af4765f912c6c4831da78f700dbadcae25b57cf9750660"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "e05fe00b8d5afd64f8bd3df39ab1a828364e6fd7849105155e34ecacaae195bc"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfrename"
  desc "Rename Terraform resources, data sources, modules, variables, outputs, and locals across .tf files"
  homepage "https://github.com/winebarrel/tfrename"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrename"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfrename"]
    end
  end

  # No zap stanza required

end
