# This file was generated by GoReleaser. DO NOT EDIT.
cask "tfrename" do
  version "1.0.4"

  on_macos do
    on_intel do
      sha256 "90b7e4a298450f54bf6d71eacda6ce38551f25b79b13355d7ee84df31139764e"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cd7a7762f77281b4c38ede6e5b77c485c0ec858a771af24b98f803f90480dbae"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "957cdf133e066c11025f3764aa8b572c96219802b0fcf238544cc6589bf0f935"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "02471fb9452e6757314f3f07e5de4463b0377f2e6742e6b17f74cfe4a4e1138a"
      url "https://github.com/winebarrel/tfrename/releases/download/v#{version}/tfrename_#{version}_linux_arm64.tar.gz"
    end
  end

  name "tfrename"
  desc "Rename Terraform resources, data sources, modules, variables, outputs, and locals across .tf files"
  homepage "https://github.com/winebarrel/tfrename"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tfrename"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tfrename"]
    end
  end

  # No zap stanza required

end
